from django.urls import path
from . import views
urlpatterns=[
    path("",views.dashboard,name="dashboard"),
    path("dashboard/",views.home,name="dashboard"),
    path("adduser/",views.signup,name="signup"),
    path("manage/",views.manage,name="manage"),
    path("settings/",views.settingsp,name="settings"),
    path("register/",views.register,name="register"),
    path("get_reg_no/",views.generate_student_reg_no,name="generate_reg_no"),
    path("get_fac_id/",views.generate_faculty_id,name="generate_faculty_id"),
    path("timetable/",views.timetable,name="signup"),
    path("get-departments/", views.get_departments, name="get_departments"),
    path("get-semesters/", views.get_semesters, name="get_semesters"),
    path("get-sections/", views.get_sections, name="get_sections"),
    path("get-timetable/", views.get_timetable, name="get_timetable"),
    path("add-timetable/", views.add_timetable, name="add_timetable"),
    path("delete-timetable/<int:id>/", views.delete_timetable, name="delete_timetable"),
    path('get-courses/', views.get_courses, name='get_courses'),
    path("enroll-students/", views.enroll_students, name="enroll_students"),
    path('get-faculty/', views.get_faculty, name='get_faculty'),
    path('edit-timetable/<int:slot_id>/', views.get_slot, name='get_slot'),
    path('update-timetable/', views.update_slot, name='update_slot'),
    path("get_teachers/", views.get_teachers, name="get_teachers"),
    path("get-courses-json/", views.get_courses_json, name="get_courses_json"),
    path("get_students/", views.get_students, name="get_students"),
     path("get-user/<str:role>/<str:user_id>/", views.get_user, name="get_user"),
    path("update-user/<str:role>/<str:user_id>/", views.update_user, name="update_user"),
    path("delete-user/<str:role>/<str:user_id>/", views.delete_user, name="delete_user"),
]